apiVersion: v1
kind: Pod
metadata:
  name: argocd-demo-pod
  labels:
    app: argocd-demo
spec:
  containers:
    - name: nginx
      image: nginx:latest
      ports:latest
        - containerPort: 80
